// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaVrGaRgIYlW2mdcPt38oDENzbNTNaLgU',
    appId: '1:505451685805:web:634fc09105f414a36ee324',
    messagingSenderId: '505451685805',
    projectId: 'expensepro-41e13',
    authDomain: 'expensepro-41e13.firebaseapp.com',
    storageBucket: 'expensepro-41e13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_iGbNxLlpMK875cN8t5AO3U146_lnT8Y',
    appId: '1:505451685805:android:dbfb9818c91179826ee324',
    messagingSenderId: '505451685805',
    projectId: 'expensepro-41e13',
    storageBucket: 'expensepro-41e13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLKmixrmGbxeyrONgoIiML3giLyZkyG2E',
    appId: '1:505451685805:ios:a38d6bd76d937b1b6ee324',
    messagingSenderId: '505451685805',
    projectId: 'expensepro-41e13',
    storageBucket: 'expensepro-41e13.firebasestorage.app',
    iosBundleId: 'com.example.mentorcraft2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLKmixrmGbxeyrONgoIiML3giLyZkyG2E',
    appId: '1:505451685805:ios:a38d6bd76d937b1b6ee324',
    messagingSenderId: '505451685805',
    projectId: 'expensepro-41e13',
    storageBucket: 'expensepro-41e13.firebasestorage.app',
    iosBundleId: 'com.example.mentorcraft2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBaVrGaRgIYlW2mdcPt38oDENzbNTNaLgU',
    appId: '1:505451685805:web:e5439a7fd6c8c8af6ee324',
    messagingSenderId: '505451685805',
    projectId: 'expensepro-41e13',
    authDomain: 'expensepro-41e13.firebaseapp.com',
    storageBucket: 'expensepro-41e13.firebasestorage.app',
  );
}
